[build]
target = "thumbv7em-none-eabihf"

# [target.'cfg(all(target_arch = "arm", target_os = "none"))']
[target.thumbv7em-none-eabihf]
runner = 'probe-rs run --chip STM32F411CEUx --connect-under-reset'
rustflags = ["-C", "link-arg=-Tlink.x", "-C", "link-arg=-Tdefmt.x"]

[env]
DEFMT_LOG = "trace"
